/* Generated By:JavaCC: Do not edit this line. DotParserConstants.java */
package br.jabuti.graph.layout.graphviz;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface DotParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GRAPH = 6;
  /** RegularExpression Id. */
  int NODE = 7;
  /** RegularExpression Id. */
  int TO = 8;
  /** RegularExpression Id. */
  int DIGRAPH = 9;
  /** RegularExpression Id. */
  int POS = 10;
  /** RegularExpression Id. */
  int BBOX = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int LBRACE = 14;
  /** RegularExpression Id. */
  int RBRACE = 15;
  /** RegularExpression Id. */
  int LBRACKET = 16;
  /** RegularExpression Id. */
  int RBRACKET = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int DOT = 20;
  /** RegularExpression Id. */
  int EQUALS = 21;
  /** RegularExpression Id. */
  int QUOTE = 22;
  /** RegularExpression Id. */
  int GT = 23;
  /** RegularExpression Id. */
  int LT = 24;
  /** RegularExpression Id. */
  int HOOK = 25;
  /** RegularExpression Id. */
  int COLON = 26;
  /** RegularExpression Id. */
  int EQ = 27;
  /** RegularExpression Id. */
  int LE = 28;
  /** RegularExpression Id. */
  int GE = 29;
  /** RegularExpression Id. */
  int NE = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int STAR = 33;
  /** RegularExpression Id. */
  int SLASH = 34;
  /** RegularExpression Id. */
  int REM = 35;
  /** RegularExpression Id. */
  int POWER = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int NODEIDENT = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;
  /** RegularExpression Id. */
  int STRING = 41;
  /** RegularExpression Id. */
  int NUMBER = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"graph\"",
    "\"node\"",
    "\"->\"",
    "\"digraph\"",
    "\"pos\"",
    "\"bb\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"\\\"\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "<LETTER>",
    "<DIGIT>",
    "<NODEIDENT>",
    "<IDENTIFIER>",
    "<STRING>",
    "<NUMBER>",
  };

}
