/*  Copyright 2003  Auri Marcelo Rizzo Vicenzi, Marcio Eduardo Delamaro, 			    Jose Carlos Maldonado

    This file is part of Jabuti.

    Jabuti is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as 
    published by the Free Software Foundation, either version 3 of the      
    License, or (at your option) any later version.

    Jabuti is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Jabuti.  If not, see <http://www.gnu.org/licenses/>.
*/


/* Generated By:JavaCC: Do not edit this line. ASMParseConstants.java */
package br.jabuti.instrumenter;

public interface ASMParseConstants {

  int EOF = 0;
  int LPAREN = 6;
  int RPAREN = 7;
  int LBRACE = 8;
  int RBRACE = 9;
  int LBRACKET = 10;
  int RBRACKET = 11;
  int SEMICOLON = 12;
  int COMMA = 13;
  int DOT = 14;
  int ASSIGN = 15;
  int GT = 16;
  int LT = 17;
  int HOOK = 18;
  int COLON = 19;
  int EQ = 20;
  int LE = 21;
  int GE = 22;
  int NE = 23;
  int PLUS = 24;
  int MINUS = 25;
  int STAR = 26;
  int SLASH = 27;
  int REM = 28;
  int POWER = 29;
  int FIELD = 30;
  int LOCAL = 31;
  int PRIVATE = 32;
  int PROTECTED = 33;
  int PUBLIC = 34;
  int INIT = 35;
  int DEFAUL = 36;
  int CASE = 37;
  int AALOAD = 38;
  int AASTORE = 39;
  int ACONST_NULL = 40;
  int ALOAD = 41;
  int ALOAD_0 = 42;
  int ALOAD_1 = 43;
  int ALOAD_2 = 44;
  int ANEWARRAY = 45;
  int ARETURN = 46;
  int ARRAYLENGTH = 47;
  int ASTORE = 48;
  int ASTORE_0 = 49;
  int ASTORE_1 = 50;
  int ASTORE_2 = 51;
  int ATHROW = 52;
  int BALOAD = 53;
  int BASTORE = 54;
  int BIPUSH = 55;
  int BREAKPOINT = 56;
  int CALOAD = 57;
  int CASTORE = 58;
  int CHECKCAST = 59;
  int D2F = 60;
  int D2I = 61;
  int D2L = 62;
  int DADD = 63;
  int DALOAD = 64;
  int DASTORE = 65;
  int DCMPG = 66;
  int DCMPL = 67;
  int DCONST = 68;
  int DCONST_0 = 69;
  int DCONST_1 = 70;
  int DDIV = 71;
  int DLOAD = 72;
  int DMUL = 73;
  int DNEG = 74;
  int DREM = 75;
  int DRETURN = 76;
  int DSUB = 77;
  int DUP = 78;
  int DUP_X1 = 79;
  int DUP_X2 = 80;
  int DUP2 = 81;
  int DUP2_X1 = 82;
  int DUP2_X2 = 83;
  int F2D = 84;
  int F2I = 85;
  int F2L = 86;
  int FADD = 87;
  int FALOAD = 88;
  int FASTORE = 89;
  int FCMPG = 90;
  int FCMPL = 91;
  int FCONST = 92;
  int FCONST_0 = 93;
  int FCONST_1 = 94;
  int FCONST_2 = 95;
  int FDIV = 96;
  int FLOAD = 97;
  int FMUL = 98;
  int FNEG = 99;
  int FREM = 100;
  int FRETURN = 101;
  int FSTORE = 102;
  int FSUB = 103;
  int GETFIELD = 104;
  int GETSTATIC = 105;
  int GOTO = 106;
  int GOTO_W = 107;
  int I2B = 108;
  int I2C = 109;
  int I2D = 110;
  int I2F = 111;
  int I2L = 112;
  int I2S = 113;
  int IADD = 114;
  int IALOAD = 115;
  int IAND = 116;
  int IASTORE = 117;
  int ICONST = 118;
  int ICONST_0 = 119;
  int ICONST_1 = 120;
  int ICONST_2 = 121;
  int ICONST_3 = 122;
  int ICONST_4 = 123;
  int ICONST_5 = 124;
  int ICONST_M1 = 125;
  int IDIV = 126;
  int IF_ACMPEQ = 127;
  int IF_ACMPNE = 128;
  int IF_ICMPEQ = 129;
  int IF_ICMPGE = 130;
  int IF_ICMPGT = 131;
  int IF_ICMPLE = 132;
  int IF_ICMPLT = 133;
  int IF_ICMPNE = 134;
  int IFEQ = 135;
  int IFGE = 136;
  int IFGT = 137;
  int IFLE = 138;
  int IFLT = 139;
  int IFNE = 140;
  int IFNONNULL = 141;
  int IFNULL = 142;
  int IINC = 143;
  int ILOAD = 144;
  int ILOAD_0 = 145;
  int ILOAD_1 = 146;
  int ILOAD_2 = 147;
  int IMPDEP_1 = 148;
  int IMPDEP_2 = 149;
  int IMUL = 150;
  int INEG = 151;
  int INSTANCEOF = 152;
  int INVOKEINTERFACE = 153;
  int INVOKESPECIAL = 154;
  int INVOKESTATIC = 155;
  int INVOKEVIRTUAL = 156;
  int IOR = 157;
  int IREM = 158;
  int IRETURN = 159;
  int ISHL = 160;
  int ISHR = 161;
  int ISTORE = 162;
  int ISTORE_0 = 163;
  int ISTORE_1 = 164;
  int ISTORE_2 = 165;
  int ISUB = 166;
  int IUSHR = 167;
  int IXOR = 168;
  int JSR = 169;
  int JSR_W = 170;
  int L2D = 171;
  int L2F = 172;
  int L2I = 173;
  int LADD = 174;
  int LALOAD = 175;
  int LAND = 176;
  int LASTORE = 177;
  int LCMP = 178;
  int LCONST = 179;
  int LCONST_0 = 180;
  int LCONST_1 = 181;
  int LDC = 182;
  int LDC_W = 183;
  int LDC2_W = 184;
  int LDIV = 185;
  int LLOAD = 186;
  int LMUL = 187;
  int LNEG = 188;
  int LOOKUPSWITCH = 189;
  int LOR = 190;
  int LREM = 191;
  int LRETURN = 192;
  int LSHL = 193;
  int LSHR = 194;
  int LSTORE = 195;
  int LSUB = 196;
  int LUSHR = 197;
  int LXOR = 198;
  int MONITORENTER = 199;
  int MONITOREXIT = 200;
  int MULTIANEWARRAY = 201;
  int NEW = 202;
  int NEWARRAY = 203;
  int NOP = 204;
  int POP = 205;
  int POP2 = 206;
  int PUSH = 207;
  int PUTFIELD = 208;
  int PUTSTATIC = 209;
  int RET = 210;
  int RETURN = 211;
  int SALOAD = 212;
  int SASTORE = 213;
  int SIPUSH = 214;
  int SWAP = 215;
  int TABLESWITCH = 216;
  int WIDE = 217;
  int FIXED_POINT_LITERAL = 218;
  int INTEGER_LITERAL = 219;
  int STRING_LITERAL = 220;
  int IDENTIFIER = 221;
  int LETTER = 222;
  int DIGIT = 223;
  int PARAM = 224;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"field\"",
    "\"local\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"<init>\"",
    "\"default\"",
    "\"case\"",
    "\"AALOAD\"",
    "\"AASTORE\"",
    "\"ACONST_NULL\"",
    "\"ALOAD\"",
    "\"ALOAD_0\"",
    "\"ALOAD_1\"",
    "\"ALOAD_2\"",
    "\"ANEWARRAY\"",
    "\"ARETURN\"",
    "\"ARRAYLENGTH\"",
    "\"ASTORE\"",
    "\"ASTORE_0\"",
    "\"ASTORE_1\"",
    "\"ASTORE_2\"",
    "\"ATHROW\"",
    "\"BALOAD\"",
    "\"BASTORE\"",
    "\"BIPUSH\"",
    "\"BREAKPOINT\"",
    "\"CALOAD\"",
    "\"CASTORE\"",
    "\"CHECKCAST\"",
    "\"D2F\"",
    "\"D2I\"",
    "\"D2L\"",
    "\"DADD\"",
    "\"DALOAD\"",
    "\"DASTORE\"",
    "\"DCMPG\"",
    "\"DCMPL\"",
    "\"DCONST\"",
    "\"DCONST_0\"",
    "\"DCONST_1\"",
    "\"DDIV\"",
    "\"DLOAD\"",
    "\"DMUL\"",
    "\"DNEG\"",
    "\"DREM\"",
    "\"DRETURN\"",
    "\"DSUB\"",
    "\"DUP\"",
    "\"DUP_X1\"",
    "\"DUP_X2\"",
    "\"DUP2\"",
    "\"DUP2_X1\"",
    "\"DUP2_X2\"",
    "\"F2D\"",
    "\"F2I\"",
    "\"F2L\"",
    "\"FADD\"",
    "\"FALOAD\"",
    "\"FASTORE\"",
    "\"FCMPG\"",
    "\"FCMPL\"",
    "\"FCONST\"",
    "\"FCONST_0\"",
    "\"FCONST_1\"",
    "\"FCONST_2\"",
    "\"FDIV\"",
    "\"FLOAD\"",
    "\"FMUL\"",
    "\"FNEG\"",
    "\"FREM\"",
    "\"FRETURN\"",
    "\"FSTORE\"",
    "\"FSUB\"",
    "\"GETFIELD\"",
    "\"GETSTATIC\"",
    "\"GOTO\"",
    "\"GOTO_W\"",
    "\"I2B\"",
    "\"I2C\"",
    "\"I2D\"",
    "\"I2F\"",
    "\"I2L\"",
    "\"I2S\"",
    "\"IADD\"",
    "\"IALOAD\"",
    "\"IAND\"",
    "\"IASTORE\"",
    "\"ICONST\"",
    "\"ICONST_0\"",
    "\"ICONST_1\"",
    "\"ICONST_2\"",
    "\"ICONST_3\"",
    "\"ICONST_4\"",
    "\"ICONST_5\"",
    "\"ICONST_M1\"",
    "\"IDIV\"",
    "\"IF_ACMPEQ\"",
    "\"IF_ACMPNE\"",
    "\"IF_ICMPEQ\"",
    "\"IF_ICMPGE\"",
    "\"IF_ICMPGT\"",
    "\"IF_ICMPLE\"",
    "\"IF_ICMPLT\"",
    "\"IF_ICMPNE\"",
    "\"IFEQ\"",
    "\"IFGE\"",
    "\"IFGT\"",
    "\"IFLE\"",
    "\"IFLT\"",
    "\"IFNE\"",
    "\"IFNONNULL\"",
    "\"IFNULL\"",
    "\"IINC\"",
    "\"ILOAD\"",
    "\"ILOAD_0\"",
    "\"ILOAD_1\"",
    "\"ILOAD_2\"",
    "\"IMPDEP_1\"",
    "\"IMPDEP_2\"",
    "\"IMUL\"",
    "\"INEG\"",
    "\"INSTANCEOF\"",
    "\"INVOKEINTERFACE\"",
    "\"INVOKESPECIAL\"",
    "\"INVOKESTATIC\"",
    "\"INVOKEVIRTUAL\"",
    "\"IOR\"",
    "\"IREM\"",
    "\"IRETURN\"",
    "\"ISHL\"",
    "\"ISHR\"",
    "\"ISTORE\"",
    "\"ISTORE_0\"",
    "\"ISTORE_1\"",
    "\"ISTORE_2\"",
    "\"ISUB\"",
    "\"IUSHR\"",
    "\"IXOR\"",
    "\"JSR\"",
    "\"JSR_W\"",
    "\"L2D\"",
    "\"L2F\"",
    "\"L2I\"",
    "\"LADD\"",
    "\"LALOAD\"",
    "\"LAND\"",
    "\"LASTORE\"",
    "\"LCMP\"",
    "\"LCONST\"",
    "\"LCONST_0\"",
    "\"LCONST_1\"",
    "\"LDC\"",
    "\"LDC_W\"",
    "\"LDC2_W\"",
    "\"LDIV\"",
    "\"LLOAD\"",
    "\"LMUL\"",
    "\"LNEG\"",
    "\"LOOKUPSWITCH\"",
    "\"LOR\"",
    "\"LREM\"",
    "\"LRETURN\"",
    "\"LSHL\"",
    "\"LSHR\"",
    "\"LSTORE\"",
    "\"LSUB\"",
    "\"LUSHR\"",
    "\"LXOR\"",
    "\"MONITORENTER\"",
    "\"MONITOREXIT\"",
    "\"MULTIANEWARRAY\"",
    "\"NEW\"",
    "\"NEWARRAY\"",
    "\"NOP\"",
    "\"POP\"",
    "\"POP2\"",
    "\"PUSH\"",
    "\"PUTFIELD\"",
    "\"PUTSTATIC\"",
    "\"RET\"",
    "\"RETURN\"",
    "\"SALOAD\"",
    "\"SASTORE\"",
    "\"SIPUSH\"",
    "\"SWAP\"",
    "\"TABLESWITCH\"",
    "\"WIDE\"",
    "<FIXED_POINT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<PARAM>",
  };

}
